input_path: "/path/to/your/mop_preprocess/output/folder"
comparison: ""

reference: "/path/to/your/ref.fa"
output: "/path/to/your/mop_mod/output/folder"
pars_tools: "${projectDir}/tools_opt.tsv"

# flows
epinano: "NO"
nanocompore: "NO"
tombo_lsc: "NO"
tombo_msc: "NO"
modphred: "YES"

# epinano plots
epinano_plots: "NO"
email: ""
