| File name (list of predicted m6A sites) | Method                           | Cell line | Species | Technology | Number of m6A sites | Study that produced the sequencing data | Study that produced the m6A sites list based on the data | Genome annotation |
|-----------------------------------------|----------------------------------|-----------|---------|------------|----------------------|-----------------------------------------|-------------------------------------------------------|-------------------|
| hg38-GLORI-seq-m6A-sites-HEK293T.bed     | GLORI-seq                        | HEK293T   | Human   | Illumina   | 170,240              | Liu et al., 2023                        | Liu et al., 2023                                      | hg38              |
| hg38-GLORI-seq-m6A-sites-HEK293T_cov25   | GLORI-seq                        | HEK293T   | Human   | Illumina   | 37,749               | Liu et al., 2023                        | Liu et al., 2023                                      | hg38              |
| hg38-m6A_sites_HEK293T_miCLIP_correct.bed | miCLIP                           | HEK293T   | Human   | Illumina   | 43,663               | NA                                      | NA                                                    | hg38              |
| hg38-m6A_sites_HEK293T_miCLIP_cov25.bed  | miCLIP                           | HEK293T   | Human   | Illumina   | 17,228               | NA                                      | NA                                                    | hg38              |
| hg38-m6ACE_m6A_sites.bed                 | m6ACE-seq                        | HEK293T   | Human   | Illumina   | 15,073               | Pratanwanich et al. Nature Biotechnology 2021 | Pratanwanich et al. Nature Biotechnology 2021         | hg38              |
| hg38-m6ACE_m6A_sites_cov25.bed           | m6ACE-seq                        | HEK293T   | Human   | Illumina   | 8,869                | Pratanwanich et al. Nature Biotechnology 2021 | Pratanwanich et al. Nature Biotechnology 2021         | hg38              |
| hg38-m6A_net_sites.bed                   | direct RNA (m6Anet algorithm)     | HEK293T   | Human   | Nanopore   | 3,119                | Pratanwanich et al. Nature Biotechnology 2021 | Hendra et al., Nature Methods 2022                    | hg38              |
| hg38-m6A_net_sites_cov25.bed             | direct RNA (m6Anet algorithm)     | HEK293T   | Human   | Nanopore   | 3,065                | Pratanwanich et al. Nature Biotechnology 2021 | Hendra et al., Nature Methods 2023                    | hg38              |
| hg38-XPORE_m6A_sites_with_scores.bed     | direct RNA (xPore algorithm)      | HEK293T   | Human   | Nanopore   | 7,203                | Pratanwanich et al. Nature Biotechnology 2021 | Pratanwanich et al. Nature Biotechnology 2021         | hg38              |
| hg38-XPORE_m6A_sites_cov25.bed           | direct RNA (xPore algorithm)      | HEK293T   | Human   | Nanopore   | 7,181                | Pratanwanich et al. Nature Biotechnology 2021 | Pratanwanich et al. Nature Biotechnology 2021         | hg38              |
